stages:
  - stop_env

stop_review:
  tags:
    - docker
    - miquido
  image: docker/compose:alpine-1.29.2
  before_script:
    - apk add --no-cache openssh
    - docker context create miquido-internal --description "Internal miquido docker at docker.miquido.net" --docker "host=ssh://docker.miquido.net"
    - docker version
    - docker-compose version
  stage: stop_env
  script:
    - ssh ubuntu@docker.miquido.net "rm -rf /docker/gitlab-dynamic-environments/sites/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    - ssh ubuntu@docker.miquido.net "rm -rf /docker/gitlab-dynamic-environments/nginx-config/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.conf"
    - docker context use miquido-internal
    - docker exec gitlab-dynamic-env_nginx_1 /etc/init.d/nginx reload
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - branches
  except:
    - main
